### ISSUE TITLE
Importing DatalayerSystem from ctrlx-datalayer package in Node app on Windows fails

### ISSUE THREAD

**Issue by ponix-net** [boschrexroth/ctrlx-automation-sdk#24]
Simple app in Node.js (e.g. [datalayer.client](https://github.com/boschrexroth/ctrlx-automation-sdk/tree/main/samples-node/datalayer.client)) chrashes when run on Windows with following error:

>node:internal/modules/cjs/loader:1319
>  return process.dlopen(module, path.toNamespacedPath(filename));
>                 ^
>
>Error: The specified module could not be found.
>\\?\C:\workspace\ctrlx-test\node_modules\ctrlx-datalayer\prebuilds\win32-x64\node.napi.node
>    at Module._extensions..node (node:internal/modules/cjs/loader:1319:18)
>    at Module.load (node:internal/modules/cjs/loader:1091:32)
>    at Module._load (node:internal/modules/cjs/loader:938:12)
>    at Module.require (node:internal/modules/cjs/loader:1115:19)
>    at require (node:internal/modules/helpers:130:18)
>    at load (C:\workspace\ctrlx-test\node_modules\node-gyp-build\node-gyp-build.js:22:10)
>    at Object.<anonymous> (C:\workspace\ctrlx-test\node_modules\ctrlx-datalayer\dist\addon.js:7:42)
>    at Module._compile (node:internal/modules/cjs/loader:1233:14)
>    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
>    at Module.load (node:internal/modules/cjs/loader:1091:32) {
>  code: 'ERR_DLOPEN_FAILED'
>}
>
>Node.js v20.5.1

On Linux this library is loaded with no problems.

**Comment by albrecht-j** [comment]
@ponix-net Hi do you use the package from npmjs.com? https://www.npmjs.com/package/ctrlx-datalayer

**Comment by ponix-net** [comment]
> @ponix-net Hi do you use the package from npmjs.com? https://www.npmjs.com/package/ctrlx-datalayer

Yes, exactly that one.

**Comment by albrecht-j** [comment]
@ponix-net did you installed the required libraries e.g. openssl?

**Comment by ponix-net** [comment]
All dependencies are installed. As I understand this error it tries to load some module from prebuild dll that is provided in ctrlx-dataplayer package and fails due to lack of this module.
