### ISSUE TITLE
build a snap app,occured build error, tips: `unsafe-perm` is not a valid npm option

### ISSUE THREAD

**Issue by LelandACM** [boschrexroth/ctrlx-automation-sdk#35]
node version :20.10.0
npm version:10.2.3

```
0 verbose cli /home/boschrexroth/scripts/ctrlx-automation-sdk/samples-vue-sunet/parts/sunet/install/bin/node /home/boschrexroth/scripts/ctrlx-automation-sdk/samples-vue-sunet/parts/sunet/install/bin/npm
1 info using npm@10.2.3
2 info using node@v20.10.0
3 timing npm:load:whichnode Completed in 14ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/home/boschrexroth/scripts/ctrlx-automation-sdk/samples-vue-sunet/parts/sunet/install/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/boschrexroth/scripts/ctrlx-automation-sdk/samples-vue-sunet/parts/sunet/build/.npmrc Completed in 2ms
10 timing config:load:project Completed in 6ms
11 timing config:load:file:/home/boschrexroth/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/home/boschrexroth/npm/etc/npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 13ms
17 timing npm:load:configload Completed in 13ms
18 timing config:load:flatten Completed in 2ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm config set unsafe-perm true
22 verbose argv "config" "set" "unsafe-perm" "true"
23 timing npm:load:setTitle Completed in 0ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:/home/boschrexroth/.npm/_logs/2024-01-02T10_08_54_413Z-
26 verbose logfile /home/boschrexroth/.npm/_logs/2024-01-02T10_08_54_413Z-debug-0.log
27 timing npm:load:logFile Completed in 8ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 56ms
31 info config set "unsafe-perm" "true"
32 timing command:config Completed in 3ms
33 verbose stack Error: `unsafe-perm` is not a valid npm option
33 verbose stack     at Config.set (/home/boschrexroth/scripts/ctrlx-automation-sdk/samples-vue-sunet/parts/sunet/install/lib/node_modules/npm/lib/commands/config.js:156:15)
33 verbose stack     at Config.exec (/home/boschrexroth/scripts/ctrlx-automation-sdk/samples-vue-sunet/parts/sunet/install/lib/node_modules/npm/lib/commands/config.js:118:22)
33 verbose stack     at Config.cmdExec (/home/boschrexroth/scripts/ctrlx-automation-sdk/samples-vue-sunet/parts/sunet/install/lib/node_modules/npm/lib/base-command.js:142:17)
33 verbose stack     at Npm.exec (/home/boschrexroth/scripts/ctrlx-automation-sdk/samples-vue-sunet/parts/sunet/install/lib/node_modules/npm/lib/npm.js:136:20)
33 verbose stack     at module.exports (/home/boschrexroth/scripts/ctrlx-automation-sdk/samples-vue-sunet/parts/sunet/install/lib/node_modules/npm/lib/cli-entry.js:61:15)
34 verbose cwd /home/boschrexroth/scripts/ctrlx-automation-sdk/samples-vue-sunet/parts/sunet/build
35 verbose Linux 5.15.0-91-generic
36 verbose node v20.10.0
37 verbose npm  v10.2.3
38 error `unsafe-perm` is not a valid npm option
39 verbose exit 1
40 timing npm Completed in 90ms
41 verbose code 1
42 error A complete log of this run can be found in: /home/boschrexroth/.npm/_logs/2024-01-02T10_08_54_413Z-debug-0.log

```

Output: ```38 error `unsafe-perm` is not a valid npm option``` , I tried downgrade a library version , the result is ok , but my application must use version 18.19.4 and above due to the `vite` library.

**Comment by ZmRZjFuDsDiR4qi5801F** [comment]
This issue is caused by an incompatible change of Node.js npm (20 vs. 22). For building Node.js based apps the installed Node.js version was taken (see old snapcraft.yaml), leading to a mismatch of installed Node.js and the embedded one, if not matching. We fixed this issue by building against same Node.js version as specified in new [snapcraft.yaml](https://github.com/boschrexroth/ctrlx-automation-sdk/blob/main/samples-node/datalayer.client.simple/snap/snapcraft.yaml). The Node.js package is downloaded on every build if not matching. So please ensure to have same Node.js version installed as targeted to speed up the build.

Check the latest Node.js samples and adjust you regarding.

Thank you for using the API and reporting.
